# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: node:12.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-


      - run: 
          name: Installing Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: 
          name: Testing
          command: npm test
      - run:
          name: "What was my custom environment variable?"
          command: echo ${COVERALLS_REPO_TOKEN}
      - run: 
          name: Coverage
          command: npm run cover
      - run: 
          name: Linting
          command: npm run lint
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@jayylmao.net"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "8f:17:96:23:2e:ca:4b:dc:27:78:03:17:d7:31:7f:cc"
      - run:
          name: Deploy docs to gh-pages
          command: gh-pages --dotfiles --dist docs/

      - run: npx tsc
